### ISSUE TITLE
Bug - BVA not found

### ISSUE THREAD

**Issue by lakohl** [paultag/wtf#1]
BVA (Board of Veterans Appeals) is coming up as not found, but it is on the list!

**Comment by paultag** [comment]
Are you by chance writing `/wtf is bva` or are you writing `/wtf bva`?

**Comment by lakohl** [comment]
The latter

**Comment by paultag** [comment]
Cool. will debug tonight!

**Comment by lakohl** [comment]
Not urgent! Was just playing with it � it�s super cool by the way!

**Comment by paultag** [comment]
@kharshawat found this too --

Turns out the Slack endpoint ignores case and is case sensitive. Will fix soon :+1:

**Comment by paultag** [comment]
Deployed fix
